// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: holdings.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getHoldingForUpdate = `-- name: GetHoldingForUpdate :one
SELECT user_id, card_id, shares_owned, avg_cost_basis, first_bought_at FROM holdings WHERE user_id = $1 AND card_id = $2 FOR UPDATE
`

type GetHoldingForUpdateParams struct {
	UserID uuid.UUID
	CardID uuid.UUID
}

func (q *Queries) GetHoldingForUpdate(ctx context.Context, arg GetHoldingForUpdateParams) (Holding, error) {
	row := q.db.QueryRow(ctx, getHoldingForUpdate, arg.UserID, arg.CardID)
	var i Holding
	err := row.Scan(
		&i.UserID,
		&i.CardID,
		&i.SharesOwned,
		&i.AvgCostBasis,
		&i.FirstBoughtAt,
	)
	return i, err
}

const listHoldingsByUser = `-- name: ListHoldingsByUser :many
SELECT user_id, card_id, shares_owned, avg_cost_basis, first_bought_at FROM holdings WHERE user_id = $1
`

func (q *Queries) ListHoldingsByUser(ctx context.Context, userID uuid.UUID) ([]Holding, error) {
	rows, err := q.db.Query(ctx, listHoldingsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Holding
	for rows.Next() {
		var i Holding
		if err := rows.Scan(
			&i.UserID,
			&i.CardID,
			&i.SharesOwned,
			&i.AvgCostBasis,
			&i.FirstBoughtAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertHolding = `-- name: UpsertHolding :one
INSERT INTO holdings (user_id, card_id, shares_owned, avg_cost_basis, first_bought_at)
VALUES ($1, $2, $3, $4, CASE WHEN $3::BIGINT > 0 THEN now() ELSE NULL END)
ON CONFLICT (user_id, card_id) DO UPDATE
SET shares_owned = EXCLUDED.shares_owned,
    avg_cost_basis = EXCLUDED.avg_cost_basis,
    first_bought_at = COALESCE(holdings.first_bought_at, CASE WHEN EXCLUDED.shares_owned > 0 THEN now() ELSE NULL END)
RETURNING user_id, card_id, shares_owned, avg_cost_basis, first_bought_at
`

type UpsertHoldingParams struct {
	UserID       uuid.UUID
	CardID       uuid.UUID
	SharesOwned  int64
	AvgCostBasis int64
}

// first_bought_at is set once, the first time this holding's shares_owned
// goes from nonexistent/zero to nonzero, and never overwritten afterward —
// even across a full sell-to-zero and later rebuy — backing the HOLD_CARD
// quest's "first buy" semantics (§7).
func (q *Queries) UpsertHolding(ctx context.Context, arg UpsertHoldingParams) (Holding, error) {
	row := q.db.QueryRow(ctx, upsertHolding,
		arg.UserID,
		arg.CardID,
		arg.SharesOwned,
		arg.AvgCostBasis,
	)
	var i Holding
	err := row.Scan(
		&i.UserID,
		&i.CardID,
		&i.SharesOwned,
		&i.AvgCostBasis,
		&i.FirstBoughtAt,
	)
	return i, err
}
