// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: leaderboard.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const computeLeaderboard = `-- name: ComputeLeaderboard :many
SELECT u.id AS user_id, u.username,
       CAST(u.currency_balance + COALESCE(SUM(h.shares_owned * c.current_price), 0) AS BIGINT) AS net_worth
FROM users u
LEFT JOIN holdings h ON h.user_id = u.id
LEFT JOIN cards c ON c.id = h.card_id
WHERE u.user_type = 'HUMAN'
GROUP BY u.id, u.username, u.currency_balance
ORDER BY net_worth DESC
LIMIT 100
`

type ComputeLeaderboardRow struct {
	UserID   uuid.UUID
	Username string
	NetWorth int64
}

func (q *Queries) ComputeLeaderboard(ctx context.Context) ([]ComputeLeaderboardRow, error) {
	rows, err := q.db.Query(ctx, computeLeaderboard)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ComputeLeaderboardRow
	for rows.Next() {
		var i ComputeLeaderboardRow
		if err := rows.Scan(&i.UserID, &i.Username, &i.NetWorth); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
