// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: quests.sql

package db

import (
	"context"
)

const getQuestByType = `-- name: GetQuestByType :one
SELECT id, title, description, type, target_value, reward_currency, reset_time, created_at FROM quests WHERE type = $1
`

func (q *Queries) GetQuestByType(ctx context.Context, type_ string) (Quest, error) {
	row := q.db.QueryRow(ctx, getQuestByType, type_)
	var i Quest
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Type,
		&i.TargetValue,
		&i.RewardCurrency,
		&i.ResetTime,
		&i.CreatedAt,
	)
	return i, err
}

const listQuests = `-- name: ListQuests :many
SELECT id, title, description, type, target_value, reward_currency, reset_time, created_at FROM quests ORDER BY created_at
`

func (q *Queries) ListQuests(ctx context.Context) ([]Quest, error) {
	rows, err := q.db.Query(ctx, listQuests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Quest
	for rows.Next() {
		var i Quest
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Type,
			&i.TargetValue,
			&i.RewardCurrency,
			&i.ResetTime,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
