// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: transactions.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    user_id, card_id, type, shares, price_per_share,
    total_currency_delta, resulting_balance, idempotency_key, related_transaction_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, card_id, type, shares, price_per_share, total_currency_delta, resulting_balance, idempotency_key, created_at, related_transaction_id
`

type CreateTransactionParams struct {
	UserID               uuid.UUID
	CardID               *uuid.UUID
	Type                 string
	Shares               *int64
	PricePerShare        *int64
	TotalCurrencyDelta   int64
	ResultingBalance     int64
	IdempotencyKey       *string
	RelatedTransactionID *uuid.UUID
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.UserID,
		arg.CardID,
		arg.Type,
		arg.Shares,
		arg.PricePerShare,
		arg.TotalCurrencyDelta,
		arg.ResultingBalance,
		arg.IdempotencyKey,
		arg.RelatedTransactionID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CardID,
		&i.Type,
		&i.Shares,
		&i.PricePerShare,
		&i.TotalCurrencyDelta,
		&i.ResultingBalance,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.RelatedTransactionID,
	)
	return i, err
}

const getLastTradeByUserAndCard = `-- name: GetLastTradeByUserAndCard :one
SELECT id, user_id, card_id, type, shares, price_per_share, total_currency_delta, resulting_balance, idempotency_key, created_at, related_transaction_id FROM transactions
WHERE user_id = $1 AND card_id = $2 AND type IN ('BUY', 'SELL')
ORDER BY created_at DESC LIMIT 1
`

type GetLastTradeByUserAndCardParams struct {
	UserID uuid.UUID
	CardID *uuid.UUID
}

func (q *Queries) GetLastTradeByUserAndCard(ctx context.Context, arg GetLastTradeByUserAndCardParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, getLastTradeByUserAndCard, arg.UserID, arg.CardID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CardID,
		&i.Type,
		&i.Shares,
		&i.PricePerShare,
		&i.TotalCurrencyDelta,
		&i.ResultingBalance,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.RelatedTransactionID,
	)
	return i, err
}

const getRelatedFeeTransaction = `-- name: GetRelatedFeeTransaction :one
SELECT id, user_id, card_id, type, shares, price_per_share, total_currency_delta, resulting_balance, idempotency_key, created_at, related_transaction_id FROM transactions WHERE related_transaction_id = $1 AND type = 'FEE'
`

func (q *Queries) GetRelatedFeeTransaction(ctx context.Context, relatedTransactionID *uuid.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getRelatedFeeTransaction, relatedTransactionID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CardID,
		&i.Type,
		&i.Shares,
		&i.PricePerShare,
		&i.TotalCurrencyDelta,
		&i.ResultingBalance,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.RelatedTransactionID,
	)
	return i, err
}

const getTransactionByIdempotencyKey = `-- name: GetTransactionByIdempotencyKey :one
SELECT id, user_id, card_id, type, shares, price_per_share, total_currency_delta, resulting_balance, idempotency_key, created_at, related_transaction_id FROM transactions WHERE idempotency_key = $1
`

func (q *Queries) GetTransactionByIdempotencyKey(ctx context.Context, idempotencyKey *string) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByIdempotencyKey, idempotencyKey)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CardID,
		&i.Type,
		&i.Shares,
		&i.PricePerShare,
		&i.TotalCurrencyDelta,
		&i.ResultingBalance,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.RelatedTransactionID,
	)
	return i, err
}

const listRecentTradesByUser = `-- name: ListRecentTradesByUser :many
SELECT id, user_id, card_id, type, shares, price_per_share, total_currency_delta, resulting_balance, idempotency_key, created_at, related_transaction_id FROM transactions
WHERE user_id = $1 AND type IN ('BUY', 'SELL')
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListRecentTradesByUserParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) ListRecentTradesByUser(ctx context.Context, arg ListRecentTradesByUserParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listRecentTradesByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CardID,
			&i.Type,
			&i.Shares,
			&i.PricePerShare,
			&i.TotalCurrencyDelta,
			&i.ResultingBalance,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.RelatedTransactionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByUser = `-- name: ListTransactionsByUser :many
SELECT id, user_id, card_id, type, shares, price_per_share, total_currency_delta, resulting_balance, idempotency_key, created_at, related_transaction_id FROM transactions WHERE user_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListTransactionsByUser(ctx context.Context, userID uuid.UUID) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CardID,
			&i.Type,
			&i.Shares,
			&i.PricePerShare,
			&i.TotalCurrencyDelta,
			&i.ResultingBalance,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.RelatedTransactionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumTransactionDeltasByUser = `-- name: SumTransactionDeltasByUser :one
SELECT COALESCE(SUM(total_currency_delta), 0)::bigint AS total
FROM transactions
WHERE user_id = $1
`

func (q *Queries) SumTransactionDeltasByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, sumTransactionDeltasByUser, userID)
	var total int64
	err := row.Scan(&total)
	return total, err
}
