// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user_quests.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getOrCreateUserQuestForUpdate = `-- name: GetOrCreateUserQuestForUpdate :one
INSERT INTO user_quests (user_id, quest_id, progress, reset_at)
VALUES ($1, $2, 0, $3)
ON CONFLICT (user_id, quest_id) DO UPDATE
SET user_id = user_quests.user_id
RETURNING user_id, quest_id, progress, completed_at, reset_at
`

type GetOrCreateUserQuestForUpdateParams struct {
	UserID  uuid.UUID
	QuestID uuid.UUID
	ResetAt time.Time
}

// Upserts a fresh (progress=0) row if none exists, and locks the row
// either way — INSERT ... ON CONFLICT DO UPDATE takes a row lock on
// conflict just like a plain UPDATE would, so this doubles as both
// "get or create" and "lock for the rest of this transaction."
func (q *Queries) GetOrCreateUserQuestForUpdate(ctx context.Context, arg GetOrCreateUserQuestForUpdateParams) (UserQuest, error) {
	row := q.db.QueryRow(ctx, getOrCreateUserQuestForUpdate, arg.UserID, arg.QuestID, arg.ResetAt)
	var i UserQuest
	err := row.Scan(
		&i.UserID,
		&i.QuestID,
		&i.Progress,
		&i.CompletedAt,
		&i.ResetAt,
	)
	return i, err
}

const listHumanUsersWithQualifyingHolding = `-- name: ListHumanUsersWithQualifyingHolding :many
SELECT DISTINCT h.user_id
FROM holdings h
JOIN users u ON u.id = h.user_id
WHERE u.user_type = 'HUMAN'
  AND h.shares_owned > 0
  AND h.first_bought_at IS NOT NULL
  AND h.first_bought_at <= $1
`

// Users eligible right now for the HOLD_CARD quest: a HUMAN user with a
// nonzero position first bought at or before the 24h cutoff.
func (q *Queries) ListHumanUsersWithQualifyingHolding(ctx context.Context, firstBoughtAt *time.Time) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listHumanUsersWithQualifyingHolding, firstBoughtAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserQuestsForUser = `-- name: ListUserQuestsForUser :many
SELECT
    q.id AS quest_id,
    q.title,
    q.description,
    q.type,
    q.target_value,
    q.reward_currency,
    q.reset_time,
    uq.progress AS progress,
    uq.completed_at AS completed_at,
    uq.reset_at AS reset_at
FROM quests q
LEFT JOIN user_quests uq ON uq.quest_id = q.id AND uq.user_id = $1
ORDER BY q.created_at
`

type ListUserQuestsForUserRow struct {
	QuestID        uuid.UUID
	Title          string
	Description    *string
	Type           string
	TargetValue    int32
	RewardCurrency int32
	ResetTime      string
	Progress       *int32
	CompletedAt    *time.Time
	ResetAt        *time.Time
}

func (q *Queries) ListUserQuestsForUser(ctx context.Context, userID uuid.UUID) ([]ListUserQuestsForUserRow, error) {
	rows, err := q.db.Query(ctx, listUserQuestsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserQuestsForUserRow
	for rows.Next() {
		var i ListUserQuestsForUserRow
		if err := rows.Scan(
			&i.QuestID,
			&i.Title,
			&i.Description,
			&i.Type,
			&i.TargetValue,
			&i.RewardCurrency,
			&i.ResetTime,
			&i.Progress,
			&i.CompletedAt,
			&i.ResetAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetDueUserQuests = `-- name: ResetDueUserQuests :execrows
UPDATE user_quests
SET progress = 0, completed_at = NULL, reset_at = $2
WHERE reset_at <= $1
`

type ResetDueUserQuestsParams struct {
	ResetAt   time.Time
	ResetAt_2 time.Time
}

func (q *Queries) ResetDueUserQuests(ctx context.Context, arg ResetDueUserQuestsParams) (int64, error) {
	result, err := q.db.Exec(ctx, resetDueUserQuests, arg.ResetAt, arg.ResetAt_2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setUserQuestState = `-- name: SetUserQuestState :one
UPDATE user_quests
SET progress = $3, completed_at = $4, reset_at = $5
WHERE user_id = $1 AND quest_id = $2
RETURNING user_id, quest_id, progress, completed_at, reset_at
`

type SetUserQuestStateParams struct {
	UserID      uuid.UUID
	QuestID     uuid.UUID
	Progress    int32
	CompletedAt *time.Time
	ResetAt     time.Time
}

func (q *Queries) SetUserQuestState(ctx context.Context, arg SetUserQuestStateParams) (UserQuest, error) {
	row := q.db.QueryRow(ctx, setUserQuestState,
		arg.UserID,
		arg.QuestID,
		arg.Progress,
		arg.CompletedAt,
		arg.ResetAt,
	)
	var i UserQuest
	err := row.Scan(
		&i.UserID,
		&i.QuestID,
		&i.Progress,
		&i.CompletedAt,
		&i.ResetAt,
	)
	return i, err
}
