// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: cards.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getCardByID = `-- name: GetCardByID :one
SELECT id, creator_user_id, card_type, sector, symbol, name, supply_model, total_supply, circulating_supply, creator_retained_shares, current_price, status, created_at, base_price, scale FROM cards WHERE id = $1
`

func (q *Queries) GetCardByID(ctx context.Context, id uuid.UUID) (Card, error) {
	row := q.db.QueryRow(ctx, getCardByID, id)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.CreatorUserID,
		&i.CardType,
		&i.Sector,
		&i.Symbol,
		&i.Name,
		&i.SupplyModel,
		&i.TotalSupply,
		&i.CirculatingSupply,
		&i.CreatorRetainedShares,
		&i.CurrentPrice,
		&i.Status,
		&i.CreatedAt,
		&i.BasePrice,
		&i.Scale,
	)
	return i, err
}

const getCardForUpdate = `-- name: GetCardForUpdate :one
SELECT id, creator_user_id, card_type, sector, symbol, name, supply_model, total_supply, circulating_supply, creator_retained_shares, current_price, status, created_at, base_price, scale FROM cards WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetCardForUpdate(ctx context.Context, id uuid.UUID) (Card, error) {
	row := q.db.QueryRow(ctx, getCardForUpdate, id)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.CreatorUserID,
		&i.CardType,
		&i.Sector,
		&i.Symbol,
		&i.Name,
		&i.SupplyModel,
		&i.TotalSupply,
		&i.CirculatingSupply,
		&i.CreatorRetainedShares,
		&i.CurrentPrice,
		&i.Status,
		&i.CreatedAt,
		&i.BasePrice,
		&i.Scale,
	)
	return i, err
}

const updateCardAfterTrade = `-- name: UpdateCardAfterTrade :one
UPDATE cards
SET circulating_supply = $2,
    current_price = $3
WHERE id = $1
RETURNING id, creator_user_id, card_type, sector, symbol, name, supply_model, total_supply, circulating_supply, creator_retained_shares, current_price, status, created_at, base_price, scale
`

type UpdateCardAfterTradeParams struct {
	ID                uuid.UUID
	CirculatingSupply int64
	CurrentPrice      int64
}

func (q *Queries) UpdateCardAfterTrade(ctx context.Context, arg UpdateCardAfterTradeParams) (Card, error) {
	row := q.db.QueryRow(ctx, updateCardAfterTrade, arg.ID, arg.CirculatingSupply, arg.CurrentPrice)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.CreatorUserID,
		&i.CardType,
		&i.Sector,
		&i.Symbol,
		&i.Name,
		&i.SupplyModel,
		&i.TotalSupply,
		&i.CirculatingSupply,
		&i.CreatorRetainedShares,
		&i.CurrentPrice,
		&i.Status,
		&i.CreatedAt,
		&i.BasePrice,
		&i.Scale,
	)
	return i, err
}
