// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: holdings.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getHoldingForUpdate = `-- name: GetHoldingForUpdate :one
SELECT user_id, card_id, shares_owned, avg_cost_basis FROM holdings WHERE user_id = $1 AND card_id = $2 FOR UPDATE
`

type GetHoldingForUpdateParams struct {
	UserID uuid.UUID
	CardID uuid.UUID
}

func (q *Queries) GetHoldingForUpdate(ctx context.Context, arg GetHoldingForUpdateParams) (Holding, error) {
	row := q.db.QueryRow(ctx, getHoldingForUpdate, arg.UserID, arg.CardID)
	var i Holding
	err := row.Scan(
		&i.UserID,
		&i.CardID,
		&i.SharesOwned,
		&i.AvgCostBasis,
	)
	return i, err
}

const upsertHolding = `-- name: UpsertHolding :one
INSERT INTO holdings (user_id, card_id, shares_owned, avg_cost_basis)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, card_id) DO UPDATE
SET shares_owned = EXCLUDED.shares_owned,
    avg_cost_basis = EXCLUDED.avg_cost_basis
RETURNING user_id, card_id, shares_owned, avg_cost_basis
`

type UpsertHoldingParams struct {
	UserID       uuid.UUID
	CardID       uuid.UUID
	SharesOwned  int64
	AvgCostBasis int64
}

func (q *Queries) UpsertHolding(ctx context.Context, arg UpsertHoldingParams) (Holding, error) {
	row := q.db.QueryRow(ctx, upsertHolding,
		arg.UserID,
		arg.CardID,
		arg.SharesOwned,
		arg.AvgCostBasis,
	)
	var i Holding
	err := row.Scan(
		&i.UserID,
		&i.CardID,
		&i.SharesOwned,
		&i.AvgCostBasis,
	)
	return i, err
}
