// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: index_components.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const listIndexComponentPrices = `-- name: ListIndexComponentPrices :many
SELECT ic.weight, c.current_price
FROM index_components ic
JOIN cards c ON c.id = ic.component_card_id
WHERE ic.index_card_id = $1
`

type ListIndexComponentPricesRow struct {
	Weight       pgtype.Numeric
	CurrentPrice int64
}

func (q *Queries) ListIndexComponentPrices(ctx context.Context, indexCardID uuid.UUID) ([]ListIndexComponentPricesRow, error) {
	rows, err := q.db.Query(ctx, listIndexComponentPrices, indexCardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIndexComponentPricesRow
	for rows.Next() {
		var i ListIndexComponentPricesRow
		if err := rows.Scan(&i.Weight, &i.CurrentPrice); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
