// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Card struct {
	ID                    uuid.UUID
	CreatorUserID         *uuid.UUID
	CardType              string
	Sector                *string
	Symbol                string
	Name                  string
	SupplyModel           string
	TotalSupply           *int64
	CirculatingSupply     int64
	CreatorRetainedShares int64
	CurrentPrice          int64
	Status                string
	CreatedAt             time.Time
	BasePrice             float64
	Scale                 float64
}

type Holding struct {
	UserID       uuid.UUID
	CardID       uuid.UUID
	SharesOwned  int64
	AvgCostBasis int64
}

type IndexComponent struct {
	IndexCardID     uuid.UUID
	ComponentCardID uuid.UUID
	Weight          pgtype.Numeric
}

type NewsEvent struct {
	ID            uuid.UUID
	Headline      string
	Body          *string
	Category      *string
	RelatedCardID *uuid.UUID
	CreatedAt     time.Time
}

type PriceTick struct {
	CardID *uuid.UUID
	Price  int64
	Volume int64
	Ts     time.Time
}

type Transaction struct {
	ID                   uuid.UUID
	UserID               uuid.UUID
	CardID               *uuid.UUID
	Type                 string
	Shares               *int64
	PricePerShare        *int64
	TotalCurrencyDelta   int64
	ResultingBalance     int64
	IdempotencyKey       *string
	CreatedAt            time.Time
	RelatedTransactionID *uuid.UUID
}

type User struct {
	ID               uuid.UUID
	Username         string
	CurrencyBalance  int64
	LoginStreakCount int32
	LastLoginAt      *time.Time
	CreatedAt        time.Time
	UserType         string
	PasswordHash     *string
}
