// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: news_events.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createNewsEvent = `-- name: CreateNewsEvent :one
INSERT INTO news_events (headline, body, category, related_card_id)
VALUES ($1, $2, $3, $4)
RETURNING id, headline, body, category, related_card_id, created_at
`

type CreateNewsEventParams struct {
	Headline      string
	Body          *string
	Category      *string
	RelatedCardID *uuid.UUID
}

func (q *Queries) CreateNewsEvent(ctx context.Context, arg CreateNewsEventParams) (NewsEvent, error) {
	row := q.db.QueryRow(ctx, createNewsEvent,
		arg.Headline,
		arg.Body,
		arg.Category,
		arg.RelatedCardID,
	)
	var i NewsEvent
	err := row.Scan(
		&i.ID,
		&i.Headline,
		&i.Body,
		&i.Category,
		&i.RelatedCardID,
		&i.CreatedAt,
	)
	return i, err
}

const listNewsEvents = `-- name: ListNewsEvents :many
SELECT id, headline, body, category, related_card_id, created_at FROM news_events ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListNewsEventsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListNewsEvents(ctx context.Context, arg ListNewsEventsParams) ([]NewsEvent, error) {
	rows, err := q.db.Query(ctx, listNewsEvents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NewsEvent
	for rows.Next() {
		var i NewsEvent
		if err := rows.Scan(
			&i.ID,
			&i.Headline,
			&i.Body,
			&i.Category,
			&i.RelatedCardID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
