// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: transactions.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    user_id, card_id, type, shares, price_per_share,
    total_currency_delta, resulting_balance, idempotency_key
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, card_id, type, shares, price_per_share, total_currency_delta, resulting_balance, idempotency_key, created_at
`

type CreateTransactionParams struct {
	UserID             uuid.UUID
	CardID             *uuid.UUID
	Type               string
	Shares             *int64
	PricePerShare      *int64
	TotalCurrencyDelta int64
	ResultingBalance   int64
	IdempotencyKey     *string
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.UserID,
		arg.CardID,
		arg.Type,
		arg.Shares,
		arg.PricePerShare,
		arg.TotalCurrencyDelta,
		arg.ResultingBalance,
		arg.IdempotencyKey,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CardID,
		&i.Type,
		&i.Shares,
		&i.PricePerShare,
		&i.TotalCurrencyDelta,
		&i.ResultingBalance,
		&i.IdempotencyKey,
		&i.CreatedAt,
	)
	return i, err
}

const getTransactionByIdempotencyKey = `-- name: GetTransactionByIdempotencyKey :one
SELECT id, user_id, card_id, type, shares, price_per_share, total_currency_delta, resulting_balance, idempotency_key, created_at FROM transactions WHERE idempotency_key = $1
`

func (q *Queries) GetTransactionByIdempotencyKey(ctx context.Context, idempotencyKey *string) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByIdempotencyKey, idempotencyKey)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CardID,
		&i.Type,
		&i.Shares,
		&i.PricePerShare,
		&i.TotalCurrencyDelta,
		&i.ResultingBalance,
		&i.IdempotencyKey,
		&i.CreatedAt,
	)
	return i, err
}

const listTransactionsByUser = `-- name: ListTransactionsByUser :many
SELECT id, user_id, card_id, type, shares, price_per_share, total_currency_delta, resulting_balance, idempotency_key, created_at FROM transactions WHERE user_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListTransactionsByUser(ctx context.Context, userID uuid.UUID) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CardID,
			&i.Type,
			&i.Shares,
			&i.PricePerShare,
			&i.TotalCurrencyDelta,
			&i.ResultingBalance,
			&i.IdempotencyKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumTransactionDeltasByUser = `-- name: SumTransactionDeltasByUser :one
SELECT COALESCE(SUM(total_currency_delta), 0)::bigint AS total
FROM transactions
WHERE user_id = $1
`

func (q *Queries) SumTransactionDeltasByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, sumTransactionDeltasByUser, userID)
	var total int64
	err := row.Scan(&total)
	return total, err
}
