// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const applyBalanceDelta = `-- name: ApplyBalanceDelta :one
UPDATE users
SET currency_balance = currency_balance + $2
WHERE id = $1
RETURNING id, username, currency_balance, login_streak_count, last_login_at, created_at, user_type, password_hash
`

type ApplyBalanceDeltaParams struct {
	ID              uuid.UUID
	CurrencyBalance int64
}

func (q *Queries) ApplyBalanceDelta(ctx context.Context, arg ApplyBalanceDeltaParams) (User, error) {
	row := q.db.QueryRow(ctx, applyBalanceDelta, arg.ID, arg.CurrencyBalance)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.CurrencyBalance,
		&i.LoginStreakCount,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UserType,
		&i.PasswordHash,
	)
	return i, err
}

const applyDailyReward = `-- name: ApplyDailyReward :one
UPDATE users
SET currency_balance = currency_balance + $2,
    last_login_at = $3,
    login_streak_count = $4
WHERE id = $1
RETURNING id, username, currency_balance, login_streak_count, last_login_at, created_at, user_type, password_hash
`

type ApplyDailyRewardParams struct {
	ID               uuid.UUID
	CurrencyBalance  int64
	LastLoginAt      *time.Time
	LoginStreakCount int32
}

func (q *Queries) ApplyDailyReward(ctx context.Context, arg ApplyDailyRewardParams) (User, error) {
	row := q.db.QueryRow(ctx, applyDailyReward,
		arg.ID,
		arg.CurrencyBalance,
		arg.LastLoginAt,
		arg.LoginStreakCount,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.CurrencyBalance,
		&i.LoginStreakCount,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UserType,
		&i.PasswordHash,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password_hash)
VALUES ($1, $2)
RETURNING id, username, currency_balance, login_streak_count, last_login_at, created_at, user_type, password_hash
`

type CreateUserParams struct {
	Username     string
	PasswordHash *string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.CurrencyBalance,
		&i.LoginStreakCount,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UserType,
		&i.PasswordHash,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, currency_balance, login_streak_count, last_login_at, created_at, user_type, password_hash FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.CurrencyBalance,
		&i.LoginStreakCount,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UserType,
		&i.PasswordHash,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, currency_balance, login_streak_count, last_login_at, created_at, user_type, password_hash FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.CurrencyBalance,
		&i.LoginStreakCount,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UserType,
		&i.PasswordHash,
	)
	return i, err
}

const getUserForUpdate = `-- name: GetUserForUpdate :one
SELECT id, username, currency_balance, login_streak_count, last_login_at, created_at, user_type, password_hash FROM users WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetUserForUpdate(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserForUpdate, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.CurrencyBalance,
		&i.LoginStreakCount,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UserType,
		&i.PasswordHash,
	)
	return i, err
}

const listUsersByType = `-- name: ListUsersByType :many
SELECT id, username, currency_balance, login_streak_count, last_login_at, created_at, user_type, password_hash FROM users WHERE user_type = $1 ORDER BY username
`

func (q *Queries) ListUsersByType(ctx context.Context, userType string) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersByType, userType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.CurrencyBalance,
			&i.LoginStreakCount,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UserType,
			&i.PasswordHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
